version: 1
formatters:
  simple:
    format: '%(request_id)s - %(asctime)s - %(levelname)8s - %(name)s - %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
    filters: [requestIdFilter]
filters:
  requestIdFilter:
    (): api.log_config.RequestIdLogFilter
loggers:
  root:
    level: DEBUG
    handlers: 
      - console
  uvicorn.error:
    level: INFO
    handlers:
      - console
    propagate: no
  uvicorn.access:
    level: INFO
    handlers:
      - console
    propagate: no
